# Generated by Django 2.0.4 on 2018-05-15 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referral', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('attachment', models.FileField(max_length=255, upload_to='email_attachments/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='EmailedReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvested', models.DateTimeField(auto_now_add=True)),
                ('received', models.DateTimeField(blank=True, editable=False, null=True)),
                ('email_uid', models.CharField(max_length=256)),
                ('to_email', models.CharField(max_length=256)),
                ('from_email', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=512)),
                ('body', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referral.Referral')),
            ],
        ),
        migrations.CreateModel(
            name='RegionAssignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='referral.Region')),
                ('user', models.ForeignKey(help_text='Default assigned user for this region.', limit_choices_to={'groups__name__in': ['PRS user'], 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='emailed_referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='harvester.EmailedReferral'),
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referral.Record'),
        ),
    ]
