# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('attachment', models.FileField(max_length=255, upload_to='email_attachments/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='EmailedReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvested', models.DateTimeField(auto_now_add=True)),
                ('received', models.DateTimeField(blank=True, editable=False, null=True)),
                ('email_uid', models.CharField(max_length=256)),
                ('to_email', models.CharField(max_length=256)),
                ('from_email', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='emailed_referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='harvester.EmailedReferral'),
        ),
    ]
