# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_auto_20160401_0929'),
        ('harvester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referral.Record'),
        ),
        migrations.AddField(
            model_name='emailedreferral',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referral.Referral'),
        ),
    ]
