# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0002_auto_20160721_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailedreferral',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
