# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_auto_20160801_1408'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('harvester', '0003_emailedreferral_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionAssignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='referral.Region')),
                ('user', models.ForeignKey(help_text='Default assigned user for this region.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
