# Generated by Django 2.0 on 2017-12-06 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0005_auto_20161109_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionassignee',
            name='region',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='referral.Region'),
        ),
        migrations.AlterField(
            model_name='regionassignee',
            name='user',
            field=models.ForeignKey(help_text='Default assigned user for this region.', limit_choices_to={'groups__name__in': ['PRS user'], 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
