apiVersion: batch/v1
kind: CronJob
metadata:
  name: prs-cronjob
spec:
  # At 09:00 on Monday
  schedule: "0 9 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: prs-cronjob
            args: ["manage.py", "overdue_tasks_email"]
            env:
            - name: SITE_URL
              value: "prs.dbca.wa.gov.au"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prs-env-prod
                  key: DATABASE_URL
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: prs-env-prod
                  key: EMAIL_HOST
