apiVersion: batch/v1
kind: CronJob
metadata:
  name: prs-cronjob
spec:
  # At 09:00 on Monday
  schedule: '0 9 * * 1'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: prs-cronjob
              imagePullPolicy: IfNotPresent
              args: ['manage.py', 'overdue_tasks_email']
              envFrom:
                - secretRef:
                    name: prs-env-prod
