dist: xenial
sudo: required
language: python
cache: pip
python:
    - 3.7
services:
    - postgresql
    - docker
addons:
    postgresql: "10"
    apt:
        packages:
            - gdal-bin
            - postgresql-10-postgis-2.4
branches:
    only:
        - master
env:
    global:
        - SECRET_KEY="SecretKeyForTravis"
        - DATABASE_URL="postgis://postgres@localhost:5432/travis_ci_test"
before_install:
    - docker build -t dbcawa/prs .
    - pip install --upgrade pip
    - pip install poetry
install:
    - poetry install --verbose --no-interaction --no-ansi
before_script:
    - psql -U postgres -c "create database travis_ci_test;"
    - psql -U postgres -d travis_ci_test -c "create extension postgis;"
    - python manage.py migrate --noinput
script:
    - python manage.py test
