sudo: false
language: python
cache: pip
python:
    - "2.7"
addons:
    postgresql: "9.5"
services:
    - postgresql
branches:
    only:
        - master
        - v2.1
env:
    global:
        - SECRET_KEY=SecretKeyForTravis
        - DATABASE_URL="postgis://postgres@localhost:5432/travis_ci_test"
install:
    - psql -U postgres -c "create extension postgis"
    - pip install -r requirements.txt
    - pip install coveralls
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - python manage.py migrate --noinput
script:
    - coverage run --source="." manage.py test
after_success:
    - coveralls
