# syntax=docker/dockerfile:1
FROM typesense/typesense:26.0
MAINTAINER asi@dbca.wa.gov.au
LABEL org.opencontainers.image.source https://github.com/dbca-wa/typesense

# Create a non-root user.
ARG UID=10001
ARG GID=10001
RUN groupadd -g "${GID}" typesense \
  && useradd --no-create-home --no-log-init --uid "${UID}" --gid "${GID}" typesense

RUN chown -R typesense:typesense /opt/typesense-server
USER ${UID}
