apiVersion: batch/v1
kind: CronJob
metadata:
  name: prs-cronjob
spec:
  # Every hour between 09:00-17:00, Mon-Fri (AWST -> UTC)
  schedule: '0 1-9 * * 1-5'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: prs-cronjob
              imagePullPolicy: IfNotPresent
              args: ['manage.py', 'harvest_email_referrals', '--email-report', '--purge-email']
              envFrom:
                - secretRef:
                    name: prs-env-prod
