# Generated by Django 3.2.10 on 2021-12-20 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clearance',
            options={'ordering': ['-pk']},
        ),
    ]
