# Generated by Django 4.2.11 on 2024-04-15 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_alter_agency_creator_alter_agency_modifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postcode',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.MaxLengthValidator(32)]),
        ),
    ]
