# Generated by Django 5.2.2 on 2025-06-16 03:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_alter_location_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_history_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=20),
        ),
    ]
