apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prs-geoserver
spec:
  serviceName: prs-geoserver-uat
  template:
    spec:
      initContainers:
      - name: chown-pvc
        image: busybox
        command:
          - /bin/chown
          - -R
          - "10001:0"
          - /data/geoserver
        volumeMounts:
          - mountPath: /data/geoserver
            name: prs-geoserver-data
      containers:
      - name: prs-geoserver
        volumeMounts:
          - mountPath: /data/geoserver
            name: prs-geoserver-data
      volumes:
        - name: prs-geoserver-data
          persistentVolumeClaim:
            claimName: prs-geoserver-data-uat
