apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -uat
resources:
  - ../../base
  - cronjobs/harvest-email-referrals
  - cronjobs/overdue-task-email
  - ingress.yaml
  - pdb.yaml
  - typesense_pvc.yaml
  - geoserver_pvc.yaml
secretGenerator:
  - name: prs-env
    type: Opaque
    envs:
      - .env
labels:
  - includeSelectors: true
    pairs:
      variant: uat
patches:
  - path: celery_patch.yaml
  - path: deployment_patch.yaml
  - path: deployment_hpa_patch.yaml
  - path: service_patch.yaml
  - path: typesense_patch.yaml
  - path: typesense_service_patch.yaml
  - path: geoserver_statefulset_patch.yaml
  - path: geoserver_headless_patch.yaml
  - path: geoserver_service_patch.yaml
