apiVersion: apps/v1
kind: Deployment
metadata:
  name: prs-celery
  labels:
    app: prs-celery-prod
spec:
  selector:
    matchLabels:
      app: prs-celery-prod
  template:
    metadata:
      labels:
        app: prs-celery-prod
    spec:
      containers:
      - name: prs-celery
        command: ["celery"]
        args: ["--app", "prs2", "worker", "--autoscale", "2,4", "--max-tasks-per-child", "5", "--max-memory-per-child", "1572864", "--loglevel", "INFO", "--events", "--without-heartbeat", "--without-gossip", "--without-mingle"]
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: prs-env-prod
              key: DATABASE_URL
        - name: TYPESENSE_HOST
          valueFrom:
            secretKeyRef:
              name: prs-env-prod
              key: TYPESENSE_HOST
        - name: TYPESENSE_API_KEY
          valueFrom:
            secretKeyRef:
              name: prs-env-prod
              key: TYPESENSE_API_KEY
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: prs-env-prod
              key: CELERY_BROKER_URL
        - name: AZURE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: prs-env-prod
              key: AZURE_ACCOUNT_NAME
        - name: AZURE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: prs-env-prod
              key: AZURE_ACCOUNT_KEY
        - name: AZURE_CONTAINER
          valueFrom:
            secretKeyRef:
              name: prs-env-prod
              key: AZURE_CONTAINER
