apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
resources:
  - ../../base
  - cronjobs/harvest-email-referrals
  - cronjobs/overdue-task-email
  - ingress.yaml
  - pdb.yaml
  - typesense_pvc.yaml
secretGenerator:
  - name: prs-env
    type: Opaque
    envs:
      - .env
generatorOptions:
  disableNameSuffixHash: true
labels:
  - includeSelectors: true
    pairs:
      variant: prod
patches:
  - path: celery_patch.yaml
  - path: deployment_patch.yaml
  - path: deployment_hpa_patch.yaml
  - path: service_patch.yaml
  - path: typesense_patch.yaml
  - path: typesense_service_patch.yaml
images:
  - name: ghcr.io/dbca-wa/prs
    newTag: 2.6.0
    # digest: sha256:f26df49390216925fb446e8fd27ea6466a739b3bcc0fd2b6a24997a5a92f81c0
