apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
resources:
  - ../../base
  - cronjobs/harvest-email-referrals
  - cronjobs/overdue-task-email
  - ingress.yaml
  - pdb.yaml
  - typesense_pvc.yaml
  - geoserver_pvc.yaml
secretGenerator:
  - name: prs-env
    type: Opaque
    envs:
      - .env
labels:
  - pairs:
      variant: prod
    includeSelectors: true
patches:
  - path: celery_patch.yaml
  - path: deployment_patch.yaml
  - path: service_patch.yaml
  - path: typesense_patch.yaml
  - path: typesense_service_patch.yaml
  - path: geoserver_patch.yaml
  - path: geoserver_service_patch.yaml
images:
  - name: ghcr.io/dbca-wa/prs
    newTag: 2.5.39
