apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prs-deployment-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: prs-deployment
      variant: prod
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prs-celery-pdb
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: prs-celery
      variant: prod
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prs-typesense-pdb
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: prs-typesense
      variant: prod
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prs-geoserver-pdb
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: prs-geoserver
      variant: prod
