apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prs-deployment-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: prs-prod
      variant: prod
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prs-celery-pdb
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: prs-celery-prod
      variant: prod
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prs-typesense-pdb
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: prs-typesense-prod
      variant: prod
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prs-geoserver-pdb
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: prs-geoserver-prod
      variant: uat
