apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prs-typesense-data
spec:
  storageClassName: managed-csi-retain
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
