# Generated by Django 2.1.9 on 2019-06-24 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailedreferral',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='emailed_referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvester.EmailedReferral'),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referral.Record'),
        ),
        migrations.AlterField(
            model_name='regionassignee',
            name='region',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='referral.Region'),
        ),
        migrations.AlterField(
            model_name='regionassignee',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Default assigned user for this region.', limit_choices_to={'groups__name__in': ['PRS user'], 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
