# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 01:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referral.Referral'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_user_bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clearance',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referral.Condition'),
        ),
        migrations.AlterField(
            model_name='clearance',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referral.Task'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referral.ConditionCategory'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='model_condition',
            field=models.ForeignKey(blank=True, help_text='Model text on which this condition is based', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_condition', to='referral.ModelCondition'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referral.Referral'),
        ),
        migrations.AlterField(
            model_name='location',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referral.Referral'),
        ),
        migrations.AlterField(
            model_name='modelcondition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referral.ConditionCategory'),
        ),
        migrations.AlterField(
            model_name='note',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referral.Referral'),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.ForeignKey(blank=True, help_text='The type of note (optional).', null=True, on_delete=django.db.models.deletion.PROTECT, to='referral.NoteType', verbose_name='note type'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='type',
            field=models.ForeignKey(help_text='The organisation type.', on_delete=django.db.models.deletion.PROTECT, to='referral.OrganisationType'),
        ),
        migrations.AlterField(
            model_name='record',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referral.Referral'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='[Searchable] The agency to which this referral relates.', null=True, on_delete=django.db.models.deletion.PROTECT, to='referral.Agency'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referring_org',
            field=models.ForeignKey(help_text='[Searchable] The referring organisation or individual.', on_delete=django.db.models.deletion.PROTECT, to='referral.Organisation', verbose_name='referring organisation'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='type',
            field=models.ForeignKey(help_text='[Searchable] The referral type; explanation of these categories is also found\n            in the <a href="/help/">PRS User documentation</a>.', on_delete=django.db.models.deletion.PROTECT, to='referral.ReferralType', verbose_name='referral type'),
        ),
        migrations.AlterField(
            model_name='referraltype',
            name='initial_task',
            field=models.ForeignKey(blank=True, help_text='Optional, but highly recommended.', null=True, on_delete=django.db.models.deletion.PROTECT, to='referral.TaskType'),
        ),
        migrations.AlterField(
            model_name='relatedreferral',
            name='from_referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_referral', to='referral.Referral'),
        ),
        migrations.AlterField(
            model_name='relatedreferral',
            name='to_referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_referral', to='referral.Referral'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_user',
            field=models.ForeignKey(help_text='The officer responsible for completing the task.', on_delete=django.db.models.deletion.PROTECT, related_name='refer_task_assigned_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.ForeignKey(help_text='The status of the task.', on_delete=django.db.models.deletion.PROTECT, to='referral.TaskState', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ForeignKey(help_text='The task type.', on_delete=django.db.models.deletion.PROTECT, to='referral.TaskType', verbose_name='task type'),
        ),
        migrations.AlterField(
            model_name='taskstate',
            name='task_type',
            field=models.ForeignKey(blank=True, help_text='Optional - does this state relate to a single task type only?', null=True, on_delete=django.db.models.deletion.PROTECT, to='referral.TaskType'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='initial_state',
            field=models.ForeignKey(help_text='The initial state for this task type.', on_delete=django.db.models.deletion.PROTECT, to='referral.TaskState'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referral.Agency'),
        ),
    ]
