# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_auto_20160401_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='Allowed file types: TIF,JPG,GIF,PNG,DOC,DOCX,XLS,XLSX,CSV,PDF,TXT,ZIP,MSG,QGS,XML', max_length=255, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
