# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 06:19
from __future__ import unicode_literals

#import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referral', '0003_auto_20160801_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGovernment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(200)])),
                ('slug', models.SlugField(help_text='Must be unique. Automatically generated from name.', unique=True)),
                #('slug', autoslug.fields.AutoSlugField(editable=False, help_text='Must be unique. Automatically generated from name.', populate_from='name', unique=True)),
                ('public', models.BooleanField(default=True, help_text='Is this lookup selection available to all users?')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='referral_localgovernment_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='referral_localgovernment_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='referral',
            name='lga',
            field=models.ForeignKey(blank=True, help_text='[Searchable] The LGA in which this referral resides.', null=True, on_delete=django.db.models.deletion.PROTECT, to='referral.LocalGovernment', verbose_name='local government'),
        ),
    ]
