# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 07:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_auto_20160824_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(help_text='The name/description of the record (max 512 characters).', max_length=512, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
    ]
