# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0005_auto_20161109_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='region',
            new_name='regions'
        ),
    ]
