# Generated by Django 5.2.3 on 2025-06-26 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0006_condition_search_document_condition_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='referral_history',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='task_history',
        ),
    ]
