# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0006_auto_20170607_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='slug',
            field=models.SlugField(help_text='Must be unique. Automatically generated from name.', unique=True),
        ),
        migrations.AlterField(
            model_name='conditioncategory',
            name='slug',
            field=models.SlugField(help_text='Must be unique. Automatically generated from name.', unique=True),
        ),
        migrations.AlterField(
            model_name='doptrigger',
            name='slug',
            field=models.SlugField(help_text='Must be unique. Automatically generated from name.', unique=True),
        ),
        migrations.AlterField(
            model_name='localgovernment',
            name='slug',
            field=models.SlugField(help_text='Must be unique. Automatically generated from name.', unique=True),
        ),
        migrations.AlterField(
            model_name='notetype',
            name='slug',
            field=models.SlugField(help_text='Must be unique. Automatically generated from name.', unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(help_text='Must be unique. Automatically generated from name.', unique=True),
        ),
        migrations.AlterField(
            model_name='organisationtype',
            name='slug',
            field=models.SlugField(help_text='Must be unique. Automatically generated from name.', unique=True),
        ),
        migrations.AlterField(
            model_name='referraltype',
            name='slug',
            field=models.SlugField(help_text='Must be unique. Automatically generated from name.', unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(help_text='Must be unique. Automatically generated from name.', unique=True),
        ),
        migrations.AlterField(
            model_name='taskstate',
            name='slug',
            field=models.SlugField(help_text='Must be unique. Automatically generated from name.', unique=True),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='slug',
            field=models.SlugField(help_text='Must be unique. Automatically generated from name.', unique=True),
        ),
    ]
