# Generated by Django 5.2.3 on 2025-06-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0007_remove_userprofile_referral_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='regions_str',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True),
        ),
    ]
