# Generated by Django 2.0 on 2017-12-06 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0007_auto_20171115_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localgovernment',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='referral_localgovernment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='localgovernment',
            name='modifier',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='referral_localgovernment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referraltype',
            name='initial_task',
            field=models.ForeignKey(blank=True, help_text='Optional, but highly recommended.', limit_choices_to=django.db.models.query_utils.Q(effective_to__isnull=True), null=True, on_delete=django.db.models.deletion.PROTECT, to='referral.TaskType'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='initial_state',
            field=models.ForeignKey(help_text='The initial state for this task type.', limit_choices_to=django.db.models.query_utils.Q(effective_to__isnull=True), on_delete=django.db.models.deletion.PROTECT, to='referral.TaskState'),
        ),
    ]
