# Generated by Django 5.2.3 on 2025-07-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0008_referral_regions_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='uploaded_file_content',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
