apiVersion: batch/v1
kind: CronJob
metadata:
  name: prs-cronjob
  labels:
    app: prs-cronjob
spec:
  schedule: ""
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      activeDeadlineSeconds: 300
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: prs-cronjob
              image: ghcr.io/dbca-wa/prs
              command: ["python"]
              args: ["--version"]
              env:
                - name: TZ
                  value: "Australia/Perth"
              securityContext:
                runAsNonRoot: true
                privileged: false
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
              volumeMounts:
                - mountPath: /tmp
                  name: tmpfs-ram
          volumes:
            - name: tmpfs-ram
              emptyDir:
                medium: "Memory"
