apiVersion: apps/v1
kind: Deployment
metadata:
  name: prs-celery
  labels:
    app: prs-celery
spec:
  selector:
    matchLabels:
      app: prs-celery
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prs-celery
    spec:
      containers:
        - name: prs-celery
          image: ghcr.io/dbca-wa/prs
          imagePullPolicy: Always
          env:
            - name: TZ
              value: 'Australia/Perth'
          resources:
            requests:
              memory: '128Mi'
              cpu: '10m'
            limits:
              memory: '2Gi'
              cpu: '1000m'
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmpfs-ram
      volumes:
        - name: tmpfs-ram
          emptyDir:
            medium: 'Memory'
      restartPolicy: Always
      automountServiceAccountToken: false
      tolerations:
        - key: arch
          operator: Equal
          value: arm64
          effect: NoSchedule
      affinity:
        # Set a node affinity to favour ARM64-based nodes (preference only).
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: arch
                    operator: In
                    values:
                      - arm64
