apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: prs-deployment-hpa
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
  metrics:
    - resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 500
      type: Resource
