apiVersion: apps/v1
kind: Deployment
metadata:
  name: prs-geoserver
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
      - name: prs-geoserver
        image: ghcr.io/dbca-wa/docker-geoserver:2.24.1
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: "Australia/Perth"
        - name: GEOSERVER_CSRF_WHITELIST
          value: ".dbca.wa.gov.au"
        resources:
          requests:
            memory: "256Mi"
            cpu: "10m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        startupProbe:
          httpGet:
            path: "/geoserver/ows?service=WFS&acceptversions=2.0.0&request=GetCapabilities"
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: "/geoserver/ows?service=WFS&acceptversions=2.0.0&request=GetCapabilities"
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: "/geoserver/ows?service=WFS&acceptversions=2.0.0&request=GetCapabilities"
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        securityContext:
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          # Note that Geoserver can't cope with a RO root filesystem.
          readOnlyRootFilesystem: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 180
