apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prs-geoserver
  labels:
    app: prs-geoserver
spec:
  selector:
    matchLabels:
      app: prs-geoserver
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: prs-geoserver
    spec:
      terminationGracePeriodSeconds: 180
      containers:
      - name: prs-geoserver
        image: ghcr.io/dbca-wa/docker-geoserver:2.24.2
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: "Australia/Perth"
        - name: GEOSERVER_CSRF_WHITELIST
          value: ".dbca.wa.gov.au"
        resources:
          requests:
            memory: "256Mi"
            cpu: "10m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        startupProbe:
          httpGet:
            path: "/geoserver/ows?service=WFS&acceptversions=2.0.0&request=GetCapabilities"
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: "/geoserver/ows?service=WFS&acceptversions=2.0.0&request=GetCapabilities"
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: "/geoserver/ows?service=WFS&acceptversions=2.0.0&request=GetCapabilities"
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        securityContext:
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          # Note that Geoserver can't cope with a RO root filesystem.
          readOnlyRootFilesystem: false
