apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prs-typesense
  labels:
    app: prs-typesense
spec:
  selector:
    matchLabels:
      app: prs-typesense
  replicas: 1
  minReadySeconds: 10
  serviceName: prs-typesense
  template:
    metadata:
      labels:
        app: prs-typesense
    spec:
      containers:
        - name: prs-typesense
          image: ghcr.io/dbca-wa/typesense:29.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: 'Australia/Perth'
            - name: TYPESENSE_DATA_DIR
              value: '/data'
          resources:
            requests:
              memory: '128Mi'
              cpu: '10m'
            limits:
              memory: '2Gi'
              cpu: '1000m'
          startupProbe:
            httpGet:
              path: /health/
              port: 8108
              scheme: HTTP
            # Typesense requires sufficient time load document collections.
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/
              port: 8108
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/
              port: 8108
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          securityContext:
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 180
      automountServiceAccountToken: false
      tolerations:
        - key: arch
          operator: Equal
          value: arm64
          effect: NoSchedule
      affinity:
        # Set a node affinity to favour ARM64-based nodes (preference only).
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: arch
                    operator: In
                    values:
                      - arm64
