apiVersion: batch/v1
kind: CronJob
metadata:
  name: prs-cronjob
spec:
  # 09:00 on Monday (AWST -> UTC)
  schedule: '0 1 * * 1'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: prs-cronjob
              args: ['manage.py', 'overdue_tasks_email']
              envFrom:
                - secretRef:
                    name: prs-env-uat
