apiVersion: batch/v1
kind: CronJob
metadata:
  name: prs-cronjob
spec:
  # 09:00 on Monday (AWST -> UTC)
  schedule: '0 1 * * 1'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: prs-cronjob
              args: ['manage.py', 'overdue_tasks_email']
              env:
                - name: SITE_URL
                  value: 'prs-uat.dbca.wa.gov.au'
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: prs-env-uat
                      key: DATABASE_URL
                - name: EMAIL_HOST
                  valueFrom:
                    secretKeyRef:
                      name: prs-env-uat
                      key: EMAIL_HOST
                - name: EMAIL_PORT
                  valueFrom:
                    secretKeyRef:
                      name: prs-env-uat
                      key: EMAIL_PORT
          tolerations:
            - key: arch
              operator: Equal
              value: arm64
              effect: NoSchedule
