name: 'Run unit tests'

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  run_tests:
    name: Run Django Tests
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgis://postgres:postgres@localhost:5432/postgres
      LOCAL_MEDIA_STORAGE: true
    services:
      postgres:
        image: postgis/postgis:15-3.5-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      rabbitmq:
        image: rabbitmq:3-alpine
        ports:
          - 5672:5672
    steps:
      #----------------------------------------------
      # Install GDAL into the environment
      #----------------------------------------------
      - name: Install GDAL
        id: install-gdal
        run: |
          sudo apt-add-repository --yes ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes gdal-bin libgdal-dev
      #----------------------------------------------
      # Checkout repo
      #----------------------------------------------
      - name: Checkout repo
        uses: actions/checkout@v5
        id: checkout-repo
        with:
          fetch-depth: 0
      #----------------------------------------------
      # Install & configure uv
      #----------------------------------------------
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      #----------------------------------------------
      # Install project dependencies
      #----------------------------------------------
      - name: Install dependencies
        run: uv sync
      #----------------------------------------------
      # Run migrations (we need to because we have to start
      # the celery worker before running unit tests)
      #----------------------------------------------
      - name: Run DB migrations
        run: uv run python manage.py migrate
      - name: Run celery worker for tests
        run: uv run celery --app prs2 worker --loglevel error --detach
      #----------------------------------------------
      # Run unit tests
      #----------------------------------------------
      - name: Run tests
        run: |
          uv run python manage.py collectstatic
          # NOTE: we can't run tests in parallel, because setup() may break DB constraints.
          uv run python manage.py test --noinput --failfast --verbosity 0 --settings prs2.test-settings
