name: Run unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/run-tests.yml'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_tests:
    name: Run Django Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      DATABASE_URL: postgis://postgres:postgres@localhost:5432/postgres
      LOCAL_MEDIA_STORAGE: true
    permissions:
      contents: read
    services:
      postgres:
        image: postgis/postgis:16-3.5-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      rabbitmq:
        image: rabbitmq:3-alpine
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install GDAL
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes gdal-bin libgdal-dev

      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
        with:
          python-version: '3.13'
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Run DB migrations
        run: uv run python manage.py migrate

      - name: Run Celery worker for tests
        run: uv run celery --app prs worker --loglevel error --detach

      - name: Run tests
        run: |
          set -euo pipefail
          uv run python manage.py collectstatic
          # NOTE: we can't run tests in parallel, because setup() may break DB constraints.
          uv run python manage.py test --noinput --failfast --verbosity 0 --settings prs.test-settings
